server:
  port: 8082
  servlet:
    context-path: /api/v1

spring:

  jackson:
    date-format: dd:MM:yyyy

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/test
    username: "postgres"
    password: "example"
    driver-class-name: org.postgresql.Driver
    testWhileIdle: true
    validationQuery: SELECT 1

#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#    dynamic: true
#    connection-timeout: 10000
#
#stuff:
#  rabbitmq:
#    exchange: stuff.exchange
#    queue: stuff.queue
#    routingkey: stuff.routingkey



lombok:
  anyConstructor:
    addConstructorProperties: true
